### PR TITLE
Fix Door Remove Cancell

### PR DESCRIPTION
**Pull request by realmaster42**
Fixes /cancel removedoor bugging arenas.

### CODE REVIEW

**Comment by Turkey2349** [comment]
again can you explain what you are attempting to do here? I'm not quite following

**Comment by realmaster42** [comment]
/z cancel removedoor glitches the full arena doors.

The problem here is that they are not reloaded when enabling or reload, glitching arenas.

**Comment by Turkey2349** [comment]
@realmaster42 I made some changes, tell me if that looks similar to what you were trying to do

**Comment by realmaster42** [comment]
Yup.

**Comment by Turkey2349** [comment]
i would send it to you if it worked 100% still some zombie spawning problems

**Pull request closed without merging**
